### ISSUE TITLE
error in GUI  co registration and channel locations  

### ISSUE THREAD

**Issue by ahmedramly** [sccn/dipfit#1]
I'm trying to use fipfit to compute an equivalent current dipole model for each brain activity component using BESA four-shell spherical head model.
when I try to do manual co-registration the following error appears 
![Screenshot from 2019-09-10 15-47-12](https://user-images.githubusercontent.com/48057708/64618403-e044f600-d3e8-11e9-8279-72797fc86b4f.png)

and if skipped the co-registration and edited the channel info to the BESA sphere model it also doesn't work and gives the following message
![Screenshot from 2019-09-10 12-44-18](https://user-images.githubusercontent.com/48057708/64618586-34e87100-d3e9-11e9-8c7d-9708500755ad.png)

what is the possible cause?
 
 #bug

**Comment by arnodelorme** [comment]
The issue is that the version of DIPFIT you are using is only compatible with the newest version of EEGLAB.
Simply download an older version of dipfit.

http://sccn.ucsd.edu/eeglab/plugins/dipfit3.0.zip

Best wishes,

Arno

**Comment by arnodelorme** [comment]
You may also upgrade to the latest version of Dipfit 3.3 (released today) which fixes the issue.

Arno
