### ISSUE TITLE
New CED file with Elec Type

### ISSUE THREAD

**Issue by cll008** [sccn/dipfit#4]
[standard_1005_BIDS.ced](https://drive.google.com/file/d/1JaLMCfOPXJYhsNNmmK3QCayluNmKDkhi/view?usp=sharing)
Here is new elec template with labels, x, y, z, and type (and blank columns for formatting purposes). It also has some BIDS recognized types at the end `EOG`, `ECG`, etc.

We can either replace all references to standard_1005.elc in EEGLAB and dipfit, or simply package this CED with bids-matlab-tools. If former, dipfit\standard_BEM\elec might be a good location for the file. The latter is easier to implement, and I think you mentioned channel type is not critical for usual EEGLAB processing.

I made an [eeglab branch](https://github.com/sccn/eeglab/tree/elecTypeTemplate) for this. Also linking to sccn/bids-matlab-tools#64

**Comment by arnodelorme** [comment]
Yes, I think it should be in the same folder as standard_1005.elc

**Comment by arnodelorme** [comment]
The current readlocs function can import the file. I think we should ensure that this file can be used by the old version of EEGLAB.

**Comment by cll008** [comment]
The only way for old EEGLAB to read this is to include nans in the CED, in which case all the nans will also be copied to the different EEG.chanlocs fields. This is what I was questioning in sccn/bids-matlab-tools#64

Decision that needs your input: completely replace old MNI lookup template vs. package this CED with bids-matlab-tools.

**Comment by arnodelorme** [comment]
I was able to read it and I am using the old code. It simply did not add the columns but we can do

```
tmp = readlocs('standard_1005_BIDS.ced’);
tmp = eeg_checkchanlocs(tmp);
```

**Comment by cll008** [comment]
https://github.com/sccn/dipfit/blob/ecba8c96e60f21e10d60a1178263a0655e8cefe8/dipfitdefs.m#L84
Changing `standard_1005.elc` into `standard_1005_BIDS.ced` is probably the cleanest way to implement the change we want.
