### ISSUE TITLE
coordformat of new CED file

### ISSUE THREAD

**Issue by cll008** [sccn/dipfit#5]
https://github.com/sccn/dipfit/blob/9d9908785787c9c7bb3ddb2c10bc9728e542a1f0/dipfitdefs.m#L85

Now that @arnodelorme rotated XY plane of the CED file, the coordformat is not MNI.

Options:
1. Use original rotation for CED file so it is still MNI and leave rotation steps downstream (less efficient)
2. Keep current CED file and change coordformat to `EEGLAB`. This seems bad, because dipfit will no longer feature a template with MNI coordformat. I know @jiversen has some conditional code based on this, and I imagine there may be other ramifications.
3. Revert changes in dipfit. Pack CED template in EEGLAB coordformat with BIDS tools.

Given the above, do we really want to continue implementing code that forces people to use the CTF-like system? Or do revert and continue to make changes specifically for BIDS datasets?

**Comment by cll008** [comment]
Issue addressed over Zoom with @arnodelorme. Dipfit changes reverted. I will work on a BIDS branch with coordsys check and send a pull request this week.

**Comment by cll008** [comment]
Reopening this issue to track further concerns:

> It does not make sense to have a CED file with MNI coordinates and a CED file with EEGLAB coordinates. CED files should always have EEGLAB coordinates.
> MNI refer to the head model so I think it is fine to have the channel coordinate file in any format we want. We should therefore:
> 
> - Put back the CED file for the MNI model in EEGLAB coordinate format.
> 
> Arno

I agree it makes sense for CED files to have EEGLAB coordinates but don't see it as a hard rule. Anyways I mentioned reverting our git changes to the ELC file so that EEG.dipfit.coordformat = MNI is accurate. "MNI" refers to the head model, yes, but also to the coordinate system that the model exists in (or at least it represents some `cordformat` keyword in EEGLAB), and is explicitly described as a coordinate system [here](https://www.fieldtriptoolbox.org/faq/how_are_the_different_head_and_mri_coordinate_systems_defined/#details-of-the-mni-coordinate-system).

I thought we psuedo-reverted the changes this way to include channel types in the updated MNI template. If we want to use the new EEGLAB coordsys CED template, we should then also change the template.coordformat line to 'EEGLAB' or 'CTF', which has downstream ramifications. Again, if we still care about EEGLAB backwards compatibility, removing or replacing the MNI template seems a bad idea, and adding a 1005 CED template seems redundant. I argue that having `EEGLAB` coordsys in the `MNI` template is far more confusing (especially if `dipfit.coordformat` is inaccurate) and that it seems cleanest to have the new CED packed with BIDS.

**Comment by arnodelorme** [comment]
Finally fixed.
