### ISSUE TITLE
Error when importing channel locations using the "standard_1005.ced" file from dipfit 4.0 plugin

### ISSUE THREAD

**Issue by CloudyDory** [sccn/dipfit#7]
In the dipfit 4.0 plugin downloaded from EEGLAB plugin manager (http://sccn.ucsd.edu/eeglab/plugins/dipfit4.0.zip), line 84 of file "dipfitdefs.m" is:
`
template_models(2).chanfile = fullfile(folder, 'standard_BEM', 'elec', 'standard_1005.ced' );
`
This causes EEGLAB 2021.0 to use the `.\dipfit4.0\standard_BEM\elec\standard_1005.ced` file for importing channel locations. However, the ced file has empty columns and EEGLAB's `readlocs.m` cannot properly handle it, so the output from `readlocs.m` has only "labels", "theta", "radius", "X", "Y" and "type" fields. As a result, `pop_chanedit.m` will make an error at line 911:
`
Unrecognized field name "Z".
`

Using the "standard_1005.elc" file for importing channel locations can fix this problem. Is it ok to use this file by default? Are the imported channel locations correct (for standard 10-10 system)?

Best,
Zhou

**Comment by cll008** [comment]
Hi @CloudyDory. I encountered this issue the other day but cannot reproduce it now on my PC. Curious... are you on a mac?

**Comment by CloudyDory** [comment]
Hi @cll008, I am using a Windows PC. Are you importing channel locations to a new dataset by using the "standard_1005.ced" that comes with dipfit 4.0? As far as I know the latest EEGLAB 2021.0 installed dipfit 3.7 by default and does not have this problem.

**Comment by cll008** [comment]
Yes I'm on a PC and manually updated to dipfit 4.0. You know what, I thought of something over the weekend:
could you check  https://github.com/sccn/eeglab/blob/53052b11076163afd9bacb4386445a8b2671de41/functions/sigprocfunc/readlocs.m#L456

It's probably because EEGLAB@2021 still has `'blankcell', 'off'`. If you remove those arguments things should work again.

**Comment by arnodelorme** [comment]
@cll008 I realized the issue was not the blankcell but that the CED file is missing columns. I have remade it from scratch and updated DIPFIT. Please check on eeglab2021 and the dev version and let me know so I can release a new version of DIPFIT tomorrow.

**Comment by cll008** [comment]
Hi @arnodelorme, did you decide change the file to .elc and omit the other columns? We decided on using .ced because it was the only working format that had X Y Z and type. The `blankcell` option is exactly used to address the missing columns (sph and polar coords).

**Comment by arnodelorme** [comment]
There was a problem with the CED file with missing columns. How did you generate this file in the first place? So I kept the CED file but fixed it and it seems to work in both the old and the new version of EEGLAB, but please double check. Tx

**Comment by cll008** [comment]
Can you share your copy of the remade CED? The latest dipfit commit 474a2625 doesn't contain one. 
I generated it from EEGLAB. The format is messed up if you edit as .txt, but the cell separation is correct when in excel (and works in EEGLAB when `blankcell` option is removed)

**Comment by arnodelorme** [comment]
OK, it is there now. Simply pool the latest changes.

**Comment by cll008** [comment]
New file works regardless of blankcell option.
