### ISSUE TITLE
Error when calling the function from command prompt

### ISSUE THREAD

**Issue by MarceloFilipchuk** [sccn/dipfit#9]
Im calling this function from the matlab command windows to obtain the component location according to the DK atlas and I get this error:

>> EEG = eeg_compatlas(EEG)
Unrecognized function or variable 'meshfile'.

Error in eeg_compatlas (line 59)
if ~exist(meshfile, 'file')

**Comment by arnodelorme** [comment]
THis function has been fixed. Thank you.
